services:
  - type: web
    name: smartdoc-ai-backend
    env: docker
    plan: free
    autoDeploy: true

    dockerfilePath: app/Dockerfile

    envVars:
      - key: GEMINI_API_KEY
        sync: false
      - key: QA_MODEL
        sync: false
      - key: SUMMARY_MODEL
        sync: false
      - key: GEMINI_EMBEDDING_MODEL
        sync: false

    healthCheckPath: /health
